CREATE TABLE [dbo].[aspnet_Membership] (
    [ApplicationId]                          UNIQUEIDENTIFIER NOT NULL,
    [UserId]                                 UNIQUEIDENTIFIER NOT NULL,
    [Password]                               NVARCHAR (128)   NOT NULL,
    [PasswordFormat]                         INT              DEFAULT ((0)) NOT NULL,
    [PasswordSalt]                           NVARCHAR (128)   NOT NULL,
    [MobilePIN]                              NVARCHAR (16)    NULL,
    [Email]                                  NVARCHAR (256)   NULL,
    [LoweredEmail]                           NVARCHAR (256)   NULL,
    [PasswordQuestion]                       NVARCHAR (256)   NULL,
    [PasswordAnswer]                         NVARCHAR (128)   NULL,
    [IsApproved]                             BIT              NOT NULL,
    [IsLockedOut]                            BIT              NOT NULL,
    [CreateDate]                             DATETIME         NOT NULL,
    [LastLoginDate]                          DATETIME         NOT NULL,
    [LastPasswordChangedDate]                DATETIME         NOT NULL,
    [LastLockoutDate]                        DATETIME         NOT NULL,
    [FailedPasswordAttemptCount]             INT              NOT NULL,
    [FailedPasswordAttemptWindowStart]       DATETIME         NOT NULL,
    [FailedPasswordAnswerAttemptCount]       INT              NOT NULL,
    [FailedPasswordAnswerAttemptWindowStart] DATETIME         NOT NULL,
    [Comment]                                NTEXT            NULL,
    [Title]                                  NVARCHAR (50)    NULL,
    [FirstName]                              NVARCHAR (50)    NULL,
    [LastName]                               NVARCHAR (50)    NULL,
    [FullName]                               AS               ((isnull([FirstName],'')+' ')+isnull([LastName],'')),
    [CountryName]                            NVARCHAR (100)   NULL,
    [CountryCode]                            NVARCHAR (50)    NULL,
    [City]                                   NVARCHAR (50)    NULL,
    [StateCounty]                            NVARCHAR (50)    NULL,
    [AddressLine1]                           NVARCHAR (100)   NULL,
    [AddressLine2]                           NVARCHAR (100)   NULL,
    [AddressLine3]                           NVARCHAR (100)   NULL,
    [ZipCode]                                NVARCHAR (15)    NULL,
    [FullAddress]                            AS               ((((((((isnull([CountryName],'')+' ')+isnull([City],''))+' ')+isnull([AddressLine1],''))+' ')+isnull([AddressLine2],''))+' ')+isnull([ZipCode],'')),
    [PhoneNumber1]                           NVARCHAR (50)    NULL,
    [PhoneNumber2]                           NVARCHAR (50)    NULL,
    [ModifiedBy]                             UNIQUEIDENTIFIER NULL,
    [ModifiedOn]                             DATETIME         NULL,
    [ModifiedIP]                             NVARCHAR (20)    NULL,
    [Boolean1]                               BIT              NULL,
    [Boolean2]                               BIT              NULL,
    [BillingCountryName]                     NVARCHAR (100)   NULL,
    [BillingCity]                            NVARCHAR (50)    NULL,
    [BillingStateCounty]                     NVARCHAR (50)    NULL,
    [BillingAddressLine1]                    NVARCHAR (100)   NULL,
    [BillingAddressLine2]                    NVARCHAR (100)   NULL,
    [BillingZipCode]                         NVARCHAR (15)    NULL,
    [BillingFirstName]                       NVARCHAR (50)    NULL,
    [BillingLastName]                        NVARCHAR (50)    NULL,
    [Birthday]                               DATETIME         NULL,
    [PublicKey]                              NVARCHAR (MAX)   NULL,
    [LastUpdatedDate]                        DATETIME         NULL,
    [DigitalSignature]                       IMAGE            NULL,
    [DigitalSignature_FileName]              NVARCHAR (50)    NULL,
    [Birthday1]                              DATETIME         NULL,
    [FingerPrint1]                           IMAGE            NULL,
    [FingerPrint2]                           IMAGE            NULL,
    [HasFingerPrint]                         BIT              NULL,
    CONSTRAINT [PK_aspnet_Membership] PRIMARY KEY NONCLUSTERED ([UserId] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__aspnet_Me__Appli__1F98B2C1] FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[aspnet_Applications] ([ApplicationId]),
    CONSTRAINT [FK__aspnet_Me__UserI__208CD6FA] FOREIGN KEY ([UserId]) REFERENCES [dbo].[aspnet_Users] ([UserId])
);





