CREATE TABLE [dbo].[AX_Incidents_Attachments] (
    [id]                  UNIQUEIDENTIFIER CONSTRAINT [DF1_AX_Incidents_Attachments_id] DEFAULT (newid()) NOT NULL,
    [ObjectId]            UNIQUEIDENTIFIER NULL,
    [ObjectType]          INT              NULL,
    [Subject]             NVARCHAR (100)   NULL,
    [NoteText]            NVARCHAR (MAX)   NULL,
    [FileAttachment]      IMAGE            NULL,
    [FileName]            NVARCHAR (100)   NULL,
    [FileExtension]       VARCHAR (10)     NULL,
    [FileContentType]     NVARCHAR (100)   NULL,
    [FileSize]            NVARCHAR (20)    NULL,
    [IsDocument]          BIT              NULL,
    [VersionNumber]       NVARCHAR (50)    NULL,
    [Images]              IMAGE            NULL,
    [CreatedBy]           UNIQUEIDENTIFIER NULL,
    [CreatedIP]           NVARCHAR (50)    NULL,
    [CreatedOn]           DATETIME         NULL,
    [ModifiedIP]          NVARCHAR (50)    NULL,
    [ModifiedBy]          UNIQUEIDENTIFIER NULL,
    [ModifiedOn]          DATETIME         NULL,
    [ApplicationId]       UNIQUEIDENTIFIER NULL,
    [RequestedURL]        NVARCHAR (150)   NULL,
    [CreatedBy_FullName]  NVARCHAR (100)   NULL,
    [ModifiedBy_FullName] NVARCHAR (100)   NULL,
    [RequestURL]          NVARCHAR (100)   NULL,
    CONSTRAINT [PK_AX_Incidents_Attachments] PRIMARY KEY CLUSTERED ([id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AX1_Incidents_Attachments_AX_Incidents] FOREIGN KEY ([ObjectId]) REFERENCES [dbo].[AX_Incidents] ([id]) ON DELETE CASCADE
);

